name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        sdk:
          - { dir: sdk-1, build: '6200805', java: 11 }
          - { dir: sdk-2, build: '6609375', java: 11 }
          - { dir: sdk-3, build: '6858069', java: 11 }
          - { dir: sdk-4, build: '7302050', java: 11 }
          - { dir: sdk-5, build: '7583922', java: 11 }
          - { dir: sdk-6, build: '8092744', java: 11 }
          - { dir: sdk-7, build: '8512546', java: 11 }
          - { dir: sdk-8, build: '9123335', java: 11 }
          - { dir: sdk-9, build: '9477386', java: 11 }
          - { dir: sdk-10, build: '9862592', java: 17 }
          - { dir: sdk-11, build: '10406996', java: 17 }
          - { dir: sdk-12, build: '11076708', java: 17 }
          - { dir: sdk-13, build: '11479570', java: 17 }
          - { dir: sdk-16, build: '12266719', java: 17 }
          - { dir: sdk-17, build: '12700392', java: 17 }
          - { dir: sdk-19, build: '13114758', java: 17 }
          - { dir: sdk-20, build: '14742923', java: 17 }
    name: ${{ matrix.sdk.dir }} / ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.sdk.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.sdk.java }}
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: premex-ab/setup-android@main
        with:
          cmdline-tools-version: ${{ matrix.sdk.build }}

      - name: Build
        if: runner.os != 'windows'
        working-directory: ${{ matrix.sdk.dir }}
        run: ./gradlew --no-daemon assembleDebug

      - name: Build (Windows)
        if: runner.os == 'windows'
        working-directory: ${{ matrix.sdk.dir }}
        run: .\gradlew.bat --no-daemon assembleDebug

  CI:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ needs.build.result }}" != "success" ]]; then
            exit 1
          fi
